### ISSUE TITLE
Use nicer Jekyll theme

### ISSUE THREAD

**Issue by white-gecko** [FTeichmann/Jekyll-RDF-Businesscards#4]
Would it be possible to use a nicer Jekyll theme, e.g. centrarium (https://bencentra.com/centrarium/, https://github.com/bencentra/centrarium). Maybe this can also be installed as gem, I've opened a respective issue there: https://github.com/bencentra/centrarium/issues/45

We also need to clarify if it is possible to inherit from another jekyll-gem-theme

**Comment by FTeichmann** [comment]
Centrarium Style is available under the branch [centrariumstyle](https://github.com/FTeichmann/Jekyll-RDF-Businesscards/tree/centrariumstyle).
